# pool:
#   vmImage: 'ubuntu-16.04'

# Run jobs in a container: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml
# container: ubuntu:16.04

# STAGES(?):
# build
# test (tests & security scan)
# [ push to registry ]
# deploy

jobs:
  - job: Build
    displayName: Build
    steps:
      - bash: |
          #!/bin/bash
          vMajor=test
        displayName: Set Var
  - job: Test
    displayName: Test
    steps:
      - bash: |
          #!/bin/bash
          echo $vMajor
          echo I tried
        displayName: Read Var
