pool:
  vmImage: 'ubuntu-16.04'

# Run jobs in a container: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml
container: ubuntu:16.04

# STAGES(?):
# build
# test (tests & security scan)
# [ push to registry ]
# deploy

steps:
  - bash: |
      #!/bin/bash
      vMajor=test
    displayName: Set Var
  - bash: |
      #!/bin/bash
      echo vMajor
    displayName: Read Var
  - script: echo Testing on Windows!
  - script: echo Testing on Linux!
  - script: echo Deploying the code!
