pool:
  vmImage: ubuntu-16.04

container: ubuntu:16.04

variables:
  global: World

steps:
- bash: |
    #!/bin/bash
    vMajor=test
    echo "##vso[task.setvariable variable=(vMajor)]$vMajor"
  displayName: Set Var
- bash: |
    #!/bin/bash
    echo major $(vMajor)
  displayName: Set Var
- bash: |
    #!/bin/bash
    echo Hello $(global)
  displayName: Hello World
