pool:
  vmImage: ubuntu-16.04

# TODO: how easy is it to get an image from an acr repo?
container: ubuntu:16.04

variables:
  global: World

# TODO: how can I name this job?

steps:
- bash: ./scripts/version.sh
  workingDirectory: $(Build.SourcesDirectory)
  displayName: Extract Package Version
- bash: |
    #!/bin/bash
    echo $VMAJOR $VMINOR $VPATCH
    docker version
    docker-compose version
    az account show
  displayName: Read Var Bash
- bash: |
    #!/bin/bash
    echo test $TEST
  displayName: Read Pipeline
- bash: |
    #!/bin/bash
    echo Hello $GLOBAL
  displayName: Hello World
