variables:
  poolName: 'ubuntu-16.04'

jobs:
  - job: Build
    displayName: Build
    pool: $(poolName)
    # container: ubuntu:16.04
    steps:
    - bash: |
        #!/bin/bash
        vMajor=test
      displayName: Set Var
  - job: Test
    displayName: Test
    pool: $(poolName)
    # container: ubuntu:16.04
    steps:
      - bash: |
          #!/bin/bash
          echo $vMajor
          echo I tried
        displayName: Read Var
