pool:
  vmImage: 'ubuntu-16.04'

# Run jobs in a container: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml
container: ubuntu:16.04

# STAGES(?):
# build
# test (tests & security scan)
# [ push to registry ]
# deploy

stages:
  - stage: Build
    jobs:
    - job: BuildJob
      steps:
      - bash: |
        #!/bin/bash
        vMajor=test
  - stage: Test
    jobs:
    - job: TestOnWindows
      steps:
      - script: echo Testing on Windows!
    - job: TestOnLinux
      steps:
      - script: echo Testing on Linux!
  - stage: Deploy
    jobs:
    - job: Deploy
      steps:
      - script: echo Deploying the code!
