pool:
  vmImage: ubuntu-16.04

# container: ubuntu:16.04

variables:
  global: World

steps:
- bash: |
    #!/bin/bash
    PACKAGE_VERSION=$(cat package.json \
     | grep version \
     | head -1 \
     | awk -F: '{ print $2 }' \
     | sed 's/[",]//g' \
     | tr -d '[[:space:]]')
   
    IFS=. read -a PACKAGE_ARRAY <<< "$PACKAGE_VERSION"
    
    vMajor=${PACKAGE_ARRAY[0]}
    vMinor=${PACKAGE_ARRAY[1]}
    vPatch=${PACKAGE_ARRAY[2]}
    
    echo "##vso[task.setvariable variable=vMajor]$vMajor"
    echo "##vso[task.setvariable variable=vMinor]$vMinor"
    echo "##vso[task.setvariable variable=vPatch]$vPatch"

    echo $(vMajor)
    echo $(Build.Reason)
    # vMajor=test
    # echo "##vso[task.setvariable variable=(vMajor)]$vMajor"
  displayName: Set Var
- bash: |
    #!/bin/bash
    echo major $(vMajor)
  displayName: Read Var Bash
- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      echo major $(vMajor)
  displayName: Read Var Powershell
- bash: |
    #!/bin/bash
    echo Hello $(global)
  displayName: Hello World
